CREATE OR REPLACE FORCE VIEW SNX_IWS2.CASES_VIEW_QCAI
( CASEID,	CLIENTID,	PRIORITY, RECEIPTTIMESTAMP,	ORIGINALCONTENTID,
PAPERSIZE,	FILESIZE,	APPLICANTNAME,	APPLICANTPOSTALCODE,	USERID,	STAGEID	,
ASSIGNMENTTIMESTAMP,	STAGESTARTTIMESTAMP,	TOTALPAGES,	TOTALDOCUMENTS,	DELETEDPAGECOUNT,
DATAPOINTCOUNT,	IMAGEREJECTREASON,	IMRSDELIVERYTIMESTAMP,	IMRDDELIVERYTIMESTAMP,	IMRSCONTENTID,
SUBMISSIONTYPE,	PRIORORIGINALCONTENTID,	ISTEST,	ISANONYMOUS,	ISPURGED,
VERSION,	IMRSVERSION,	STATUS,	LANGUAGEID,	CLIENTFILENAME,	NOTES,
CLIENTCASENUMBER,	CREATED_TIMESTAMP,	CREATED_USERID,	CREATED_STAGEID,	UPDATED_TIMESTAMP,
UPDATED_USERID,	UPDATED_STAGEID,	DID,	ASSIGNEDBY,	ISINTERNALTEST,
IMRDCONTENTID,	LAST_BILLED_TIMESTAMP,	CODE_TYPE,	CODE_VERSION,	HIERARCHYREVISION,	DEBUG,
UPLOAD_METHOD,	SOURCE_IP_ADDR,	DUE_ON,	APPENDTOCASEID,	DELIVERYTIMESTAMP,	XMLDATA,FILESTATUS
)
AS
     SELECT  
     CASEID,	CLIENTID,	PRIORITY,	
     TO_CHAR (RECEIPTTIMESTAMP, 'YYYY-MM-DD HH24:MI.SS') AS RECEIPTTIMESTAMP,
     ORIGINALCONTENTID,     PAPERSIZE,	FILESIZE,	APPLICANTNAME,	APPLICANTPOSTALCODE,	USERID,	STAGEID	,
     TO_CHAR (ASSIGNMENTTIMESTAMP, 'YYYY-MM-DD HH24:MI.SS') AS ASSIGNMENTTIMESTAMP,
     TO_CHAR (STAGESTARTTIMESTAMP, 'YYYY-MM-DD HH24:MI.SS') AS STAGESTARTTIMESTAMP,	
     TOTALPAGES,	TOTALDOCUMENTS,	DELETEDPAGECOUNT,    DATAPOINTCOUNT,	IMAGEREJECTREASON,	
     TO_CHAR (IMRSDELIVERYTIMESTAMP, 'YYYY-MM-DD HH24:MI.SS') AS IMRSDELIVERYTIMESTAMP,	
     TO_CHAR (IMRDDELIVERYTIMESTAMP, 'YYYY-MM-DD HH24:MI.SS') AS IMRDDELIVERYTIMESTAMP,	
     IMRSCONTENTID,      SUBMISSIONTYPE,	PRIORORIGINALCONTENTID,	ISTEST,	ISANONYMOUS,	ISPURGED,
     VERSION,	IMRSVERSION,	STATUS,	LANGUAGEID,	CLIENTFILENAME,	NOTES,      CLIENTCASENUMBER,	
     TO_CHAR (CREATED_TIMESTAMP, 'YYYY-MM-DD HH24:MI.SS') AS CREATED_TIMESTAMP,	
     CREATED_USERID,	CREATED_STAGEID,	
     TO_CHAR (UPDATED_TIMESTAMP, 'YYYY-MM-DD HH24:MI.SS') AS UPDATED_TIMESTAMP,
     UPDATED_USERID,	UPDATED_STAGEID,	DID,	ASSIGNEDBY,	ISINTERNALTEST,     IMRDCONTENTID,	
     TO_CHAR (LAST_BILLED_TIMESTAMP, 'YYYY-MM-DD HH24:MI.SS') AS LAST_BILLED_TIMESTAMP,	
     CODE_TYPE,	CODE_VERSION,	HIERARCHYREVISION,	DEBUG,
     UPLOAD_METHOD,	SOURCE_IP_ADDR,	DUE_ON,	APPENDTOCASEID,	
     TO_CHAR (DELIVERYTIMESTAMP, 'YYYY-MM-DD HH24:MI.SS') AS DELIVERYTIMESTAMP,	
     XMLDATA,FILESTATUS
    FROM   CASES;
      