Drop View DPENTRYCODES_VIEW;

CREATE OR REPLACE FORCE VIEW "DPENTRYCODES_VIEW" ("DPECID", "DPENTRYID", "DPFORMENTITYID", "ENTRYTRANSCRIPTION", "DATADATE", "STATUS", "PAGEID", "SECTIONNUMBER", "CASEID", "ORIGINALPAGENUMBER", "DOCUMENTTYPEID", "DOCUMENTDATE", "CLIENTID", "CLIENTFILENAME", "CLIENTCASENUMBER", "APPLICANTNAME", "APPLICANTPOSTALCODE", "NOTES", "CODE", "CODETYPE", "CODEDESC", "ISHIDDEN", "CONFIDENCE", "CODE_STATUS", "ISCRITICAL", "CREATED_TIMESTAMP", "UPDATED_TIMESTAMP", "CREATED_USERID", "UPDATED_USERID", "CREATED_STAGEID", "UPDATED_STAGEID", "CODEID", "VERSION", "DPCATEGORYID", "DPSUBCATID", "DISPLAYLABEL", "ISDATEREQUIRED", "ISSTATUSREQUIRED")
                  AS
  SELECT A.DPECID AS DPECID,
    A.DPENTRYID   AS DPENTRYID,
    B.DPFORMENTITYID,
    B.ENTRYTRANSCRIPTION,
    B.DATADATE,
    B.STATUS,
    B.PAGEID,
    B.STARTSECTIONNUMBER,
    C.CASEID,
    C.ORIGINALPAGENUMBER,
    C.DOCUMENTTYPEID,
    C.DOCUMENTDATE,
    D.CLIENTID,
    D.CLIENTFILENAME,
    D.CLIENTCASENUMBER,
    D.APPLICANTNAME,
    D.APPLICANTPOSTALCODE,
    D.NOTES,
    A.CODE              AS CODE,
    A.CODETYPE          AS CODETYPE,
    A.CODEDESC          AS CODEDESC,
    A.ISHIDDEN          AS ISHIDDEN,
    A.CONFIDENCE        AS CONFIDENCE,
    A.STATUS            AS CODE_STATUS,
    A.ISCRITICAL        AS ISCRITICAL,
    A.CREATED_TIMESTAMP AS CREATED_TIMESTAMP,
    A.UPDATED_TIMESTAMP AS UPDATED_TIMESTAMP,
    A.CREATED_USERID    AS CREATED_USERID,
    A.UPDATED_USERID    AS UPDATED_USERID,
    A.CREATED_STAGEID   AS CREATED_STAGEID,
    A.UPDATED_STAGEID   AS UPDATED_STAGEID,
    A.CODEID            AS CODEID,
    A.VERSION           AS VERSION,
    E.DPCATEGORYID,
    E.DPSUBCATID,
    E.DISPLAYLABEL,
    E.ISDATEREQUIRED,
    E.ISSTATUSREQUIRED
  FROM DPENTRYCODES A,
    DPENTRIES B,
    PAGES C,
    CASES D,
    DPFORMENTITIES E
  WHERE B.DPENTRYID    = A.DPENTRYID
  AND C.PAGEID         = B.PAGEID
  AND D.CASEID         = C.CASEID
  AND E.DPFORMENTITYID = B.DPFORMENTITYID;