Drop View DPENTRIES_VIEW;

CREATE OR REPLACE FORCE VIEW "DPENTRIES_VIEW" ("DPENTRYID", "PAGEID", "SECTIONNUMBER", "DPFORMENTITYID", "DATAFIELD1VALUE", "DATAFIELD2VALUE", "DATAFIELD3VALUE", "DATAFIELD4VALUE", "DATADATE", "CREATED_TIMESTAMP", "CREATED_USERID", "CREATED_STAGEID", "UPDATED_TIMESTAMP", "UPDATED_USERID", "UPDATED_STAGEID")
AS
  SELECT A.DPENTRYID ,
    A.PAGEID ,
    A.STARTSECTIONNUMBER ,
    A.DPFORMENTITYID ,
    A.DATAFIELD1VALUE,
    A.DATAFIELD2VALUE,
    A.DATAFIELD3VALUE,
    A.DATAFIELD4VALUE,
    A.DATADATE,
    A.CREATED_TIMESTAMP ,
    A.CREATED_USERID ,
    A.CREATED_STAGEID ,
    A.UPDATED_TIMESTAMP ,
    A.UPDATED_USERID ,
    A.UPDATED_STAGEID
  FROM DPENTRIES A;