--View of all data points
CREATE OR REPLACE FORCE VIEW XML_DATAPOINTS_V As
Select
   c.caseid,
   regexp_substr(code.lineage,'[^/]+', 1, 1) CategoryName, 
   regexp_substr(code.lineage,'[^/]+', 1, 2) SubcategoryName, 
   dpe.dpentryId,
   dpe.hid codeid,  
   code.name codename, 
   code.CodeDesc CodeDescription, 
   code.codetype,  
   c.HIERARCHYREVISION CodeVersion,  
   dpe.datadate,  
   p.finalpagenumber page,
   case when dpe.endSectionNumber != dpe.startSectionNumber then dpe.startSectionNumber||'-'||dpe.endSectionNumber else to_char(dpe.startSectionNumber) end line,
   dpe.iscritical,
   dpe.CRITICALITY,
   dpe.status, -- data status for screening
   code.dataField1,  
   dpe.dataField1Value,  
   code.dataField2, 
   dpe.dataField2Value, 
   code.dataField3, 
   dpe.dataField3Value,  
   code.dataField4,  
   dpe.dataField4Value,  
   code.dataField5,  
   dpe.dataField5Value,  
   code.dataField6,  
   dpe.dataField6Value,  
   code.dataField7,  
   dpe.dataField7Value, 
   code.dataField8,  
   dpe.dataField8Value,  
   code.dataField9,  
   dpe.dataField9Value,  
   code.dataField10, 
   dpe.dataField10Value,  
   code.dataField11,  
   dpe.dataField11Value,  
   code.dataField12,  
   dpe.dataField12Value,
   code.dataField13, 
   dpe.dataField13Value,  
   code.dataField14,  
   dpe.dataField14Value,  
   code.dataField15,  
   dpe.dataField15Value,  
   code.dataField16,  
   dpe.dataField16Value,  
   code.dataField17,  
   dpe.dataField17Value, 
   code.dataField18,  
   dpe.dataField18Value,  
   code.dataField19,  
   dpe.dataField19Value,  
   code.dataField20, 
   dpe.dataField20Value,  
    code.DATAFIELD21,
    dpe.DATAFIELD21VALUE,
    code.DATAFIELD22,
    dpe.DATAFIELD22VALUE,
    code.DATAFIELD23,
    dpe.DATAFIELD23VALUE,
    code.DATAFIELD24,
    dpe.DATAFIELD24VALUE,
    code.DATAFIELD25,
    dpe.DATAFIELD25VALUE,
    code.DATAFIELD26,
    dpe.DATAFIELD26VALUE,
    code.DATAFIELD27,
    dpe.DATAFIELD27VALUE,
    code.DATAFIELD28,
    dpe.DATAFIELD28VALUE,
    code.DATAFIELD29,
    dpe.DATAFIELD29VALUE,
    code.DATAFIELD30,
    dpe.DATAFIELD30VALUE,
    code.DATAFIELD31,
    dpe.DATAFIELD31VALUE,
    code.DATAFIELD32,
    dpe.DATAFIELD32VALUE
   FROM dpentries dpe, pages p, MEDICALHIERARCHY_LEAF_LEVEL_V code, cases c  
   WHERE dpe.pageid = p.pageid 
   AND dpe.hid = code.hid AND dpe.isDeleted = 'N' 
   AND c.caseid = p.caseId;