set define off

DROP TABLE SNX_IWS2.QCAICODES CASCADE CONSTRAINTS;
CREATE TABLE SNX_IWS2.QCAICODES 
    ( 
     QCID INTEGER  NOT NULL , 
     CASEID INTEGER ,
     DPENTRYID INTEGER , 
     RETURNSTATUS VARCHAR2(20),
     RETURNVALUE VARCHAR2(2000),
     CONFIDENCE NUMBER(*,2) ,
     REASONING VARCHAR2(4000),
     ISCODEACCEPTED VARCHAR2(1), 
     CREATED_TIMESTAMP TIMESTAMP (4) WITH TIME ZONE,
     CREATED_USERID INTEGER,
     CREATED_STAGEID INTEGER,
     UPDATED_TIMESTAMP TIMESTAMP (4) WITH TIME ZONE,
     UPDATED_USERID INTEGER,                         
     UPDATED_STAGEID INTEGER
    ) 
;
ALTER TABLE SNX_IWS2.QCAICODES 
    ADD CONSTRAINT QCAICODES_PK PRIMARY KEY ( QCID ) using index tablespace snx_iws_inx;
CREATE INDEX SNX_IWS2.QCAICODES_IDX1 ON SNX_IWS2.QCAICODES 
    (CASEID, DPENTRYID, RETURNSTATUS, ISCODEACCEPTED) tablespace snx_iws_inx;

DROP SEQUENCE SNX_IWS2.QCAICODES_SEQ;
--Create Sequence
CREATE SEQUENCE SNX_IWS2.QCAICODES_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

--Create Trigger
CREATE OR REPLACE TRIGGER SNX_IWS2.QCAICODES_QCID_TGR before INSERT ON SNX_IWS2.QCAICODES FOR EACH row
  BEGIN
    IF inserting THEN
      select current_timestamp into :new.CREATED_TIMESTAMP from dual;
      IF :NEW.QCID IS NULL THEN
        SELECT SNX_IWS2.QCAICODES_SEQ.nextval INTO :NEW.QCID FROM dual;
      END IF;
    END IF;
  END;
/

grant all on SNX_IWS2.QCAICODES to SNX_BB2;
create synonym SNX_BB2.QCAICODES for SNX_IWS2.QCAICODES;
