CREATE TABLESPACE "SNX_FDN" DATAFILE '/ORACLE/NJCD02/snx_fdn.dbf' SIZE 10M 
AUTOEXTEND ON NEXT 10240K MAXSIZE 16000M 
LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
DEFAULT STORAGE ( ENCRYPT ) ENCRYPTION USING 'AES256';

CREATE TABLESPACE "SNX_FDN_INX" DATAFILE '/ORACLE/NJCD02/snx_fdn_inx.dbf' SIZE 10M 
AUTOEXTEND ON NEXT 10240K MAXSIZE 16000M 
LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
DEFAULT STORAGE ( ENCRYPT ) ENCRYPTION USING 'AES256';

-- USER SQL
CREATE USER SNX_FDN IDENTIFIED BY breezyland 
DEFAULT TABLESPACE "SNX_FDN"
TEMPORARY TABLESPACE "TEMP";
-- QUOTAS
ALTER USER SNX_FDN QUOTA UNLIMITED ON SNX_FDN;
ALTER USER SNX_FDN QUOTA UNLIMITED ON SNX_FDN_INX;
-- ROLES
GRANT "RESOURCE" TO SNX_FDN ;
GRANT "CONNECT" TO SNX_FDN ;
-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO SNX_FDN ;
GRANT CREATE MATERIALIZED VIEW TO SNX_FDN ;
