CREATE TABLESPACE "SNX_IWS_DW" DATAFILE '/ORACLE/NJCP01/oradata/snx_iws_dw01.dbf' SIZE 10M 
AUTOEXTEND ON NEXT 10240K MAXSIZE 16000M 
LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
DEFAULT STORAGE ( ENCRYPT ) ENCRYPTION USING 'AES256';

CREATE TABLESPACE "SNX_IWS_DW_INX" DATAFILE '/ORACLE/NJCP01/oradata/snx_iws_dw_inx01.dbf' SIZE 10M 
AUTOEXTEND ON NEXT 10240K MAXSIZE 16000M 
LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
DEFAULT STORAGE ( ENCRYPT ) ENCRYPTION USING 'AES256';

-- USER SQL
CREATE USER SNX_IWS_DW IDENTIFIED BY xxxxxxxxx 
DEFAULT TABLESPACE "SNX_IWS_DW"
TEMPORARY TABLESPACE "TEMP";
-- QUOTAS
ALTER USER SNX_IWS_DW QUOTA UNLIMITED ON SNX_IWS_DW;
ALTER USER SNX_IWS_DW QUOTA UNLIMITED ON SNX_IWS_DW_INX;
-- ROLES
GRANT "RESOURCE" TO SNX_IWS_DW ;
GRANT "CONNECT" TO SNX_IWS_DW ;
-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO SNX_IWS_DW ;
GRANT CREATE MATERIALIZED VIEW TO SNX_IWS_DW ;
GRANT CREATE SYNONYM TO SNX_IWS_DW ;

-- Object privileges
-- select 'GRANT SELECT ON SNX_IWS2.'||TABLE_NAME||' TO SNX_IWS_DW;' from user_tables;
GRANT SELECT ON SNX_IWS2.ACTIONS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.AUDITLOG TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.CASEHISTORY TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.CASES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.CLIENTS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DIVISIONS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DOCUMENTTYPEGROUPS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DOCUMENTTYPES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DPCATEGORIES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DPCATEGORYGROUPS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DPENTRIES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DPENTRYCODES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DPFORMENTITIES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DPNOTABLES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DPSUBCATEGORIES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.ERRORLOG TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.GROUPS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.HEAD TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.LANGUAGES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.LOCALIZEDTEXTS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.LOVS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.LOVVALUES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.MESSAGES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.PAGES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.ROLES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.ROLESTAGES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.SESSIONS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.STAGES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.TEAMS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.USERROLES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.USERS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.ENV_SETTINGS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.MASTERCODES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.WORKFLOWS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.CONFIG_SWITCHES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.BILLING_BATCH_DETAILS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.HTMLDB_PLAN_TABLE TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.LOCALIZEDTEXT TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.CUBE1 TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.IMAGES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.BILLING_BATCH TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.XMLTABLE TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.MEDICALHIERARCHY TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.GROUPHIERARCHY TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.CASEHISTORYSUM TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.CRITICALICDLIST TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DPENTRIES_2047_0529 TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DPENTRIES_2047_0601 TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DPENTRIES_2047_0612 TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.NDC TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.PCSXML TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.PCSCAT TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.PCSCODES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DPENTRIES_2047_0619 TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.NDCCAT TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.QCAICODES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.NDCREORDER TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.PRODUCTSPECS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DRBOBCRITICAL TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.NDC_GROUP2 TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.CLIENTZIPBATCHES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.BATCHPAYLOAD TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.IDIS_CAPRELSA TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.IDISXXX_CAPRELSA TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.PLAN_TABLE TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.USER_STATS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.USER_LISTING TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.CLIENT_STATS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.ERROR_LISTING TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.CASE_STATS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.SYNPRAW TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.SYNPRAWDOSAGE TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DR$MEDICALHIERARCHY_FTX_IDX$I TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DR$MEDICALHIERARCHY_FTX_IDX$R TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.TIME_CALENDAR_DIM TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DR$MEDICALHIERARCHY_FTX_IDX$N TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.DR$MEDICALHIERARCHY_FTX_IDX$K TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.MEDICALHIERARCHY_LEAF_LEVEL_V TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.SYNPMERGED TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.NDC_DELETE2 TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.NDC_UPDATE TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.STAGE_CODES TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.NDC_GROUP TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.NDC_UPDATE2 TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.NDC_DELETE TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.INFOPATHDATA TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.STAGE_RANGE_LOVS TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.GLOSSARYXML TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.MEDICALHIERARCHY_STAGING TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.MEDICALHIERARCHY_EXCLUSION TO SNX_IWS_DW;
GRANT SELECT ON SNX_IWS2.STAGE_EXCLUSION TO SNX_IWS_DW;

-- synonyms for dimension tables
--CREATE SYNONYM SNX_IWS_DW.DIM_CLIENTS FOR SNX_IWS2.CLIENTS;
--CREATE SYNONYM SNX_IWS_DW.DIM_CASES FOR SNX_IWS2.CASES;
--CREATE SYNONYM SNX_IWS_DW.DIM_STAGES FOR SNX_IWS2.STAGES;
--CREATE SYNONYM SNX_IWS_DW.DIM_USERS FOR SNX_IWS2.USERS;
--CREATE SYNONYM SNX_IWS_DW.DIM_CLIENTZIPBATCHES FOR SNX_IWS2.CLIENTZIPBATCHES;

-- create date dimension table
CREATE TABLE SNX_IWS_DW.DIM_DATES AS
WITH base_calendar AS
  (SELECT CurrDate          AS Day_ID,
    1                       AS Day_Time_Span,
    CurrDate                AS Day_End_Date,
    TO_CHAR(CurrDate,'Day') AS Week_Day_Full,
    TO_CHAR(CurrDate,'DY')  AS Week_Day_Short,
    TO_NUMBER(TRIM(leading '0'
  FROM TO_CHAR(CurrDate,'D'))) AS Day_Num_of_Week,
    TO_NUMBER(TRIM(leading '0'
  FROM TO_CHAR(CurrDate,'DD'))) AS Day_Num_of_Month,
    TO_NUMBER(TRIM(leading '0'
  FROM TO_CHAR(CurrDate,'DDD'))) AS Day_Num_of_Year,
    UPPER(TO_CHAR(CurrDate,'Mon')
    || '-'
    || TO_CHAR(CurrDate,'YYYY')) AS Month_ID,
    TO_CHAR(CurrDate,'Mon')
    || ' '
    || TO_CHAR(CurrDate,'YYYY') AS Month_Short_Desc,
    RTRIM(TO_CHAR(CurrDate,'Month'))
    || ' '
    || TO_CHAR(CurrDate,'YYYY') AS Month_Long_Desc,
    TO_CHAR(CurrDate,'Mon')     AS Month_Short,
    TO_CHAR(CurrDate,'Month')   AS Month_Long,
    TO_NUMBER(TRIM(leading '0'
  FROM TO_CHAR(CurrDate,'MM'))) AS Month_Num_of_Year,
    'Q'
    || UPPER(TO_CHAR(CurrDate,'Q')
    || '-'
    || TO_CHAR(CurrDate,'YYYY'))     AS Quarter_ID,
    TO_NUMBER(TO_CHAR(CurrDate,'Q')) AS Quarter_Num_of_Year,
    CASE
      WHEN TO_NUMBER(TO_CHAR(CurrDate,'Q')) <= 2
      THEN 1
      ELSE 2
    END AS half_num_of_year,
    CASE
      WHEN TO_NUMBER(TO_CHAR(CurrDate,'Q')) <= 2
      THEN 'H'
        || 1
        || '-'
        || TO_CHAR(CurrDate,'YYYY')
      ELSE 'H'
        || 2
        || '-'
        || TO_CHAR(CurrDate,'YYYY')
    END                      AS half_of_year_id,
    TO_CHAR(CurrDate,'YYYY') AS Year_ID
  FROM
    (SELECT level n,
      -- Calendar starts at the day after this date.
      TO_DATE('31/12/2009','DD/MM/YYYY') + NUMTODSINTERVAL(level,'DAY') CurrDate
    FROM dual
      -- Change for the number of days to be added to the table.
      CONNECT BY level <= 365*10
    )
  )
SELECT day_id,
  day_time_span,
  day_end_date,
  week_day_full,
  week_day_short,
  day_num_of_week,
  day_num_of_month,
  day_num_of_year,
  month_id,
  COUNT(*) OVER (PARTITION BY month_id)    AS Month_Time_Span,
  MAX(day_id) OVER (PARTITION BY month_id) AS Month_End_Date,
  month_short_desc,
  month_long_desc,
  month_short,
  month_long,
  month_num_of_year,
  quarter_id,
  COUNT(*) OVER (PARTITION BY quarter_id)    AS Quarter_Time_Span,
  MAX(day_id) OVER (PARTITION BY quarter_id) AS Quarter_End_Date,
  quarter_num_of_year,
  half_num_of_year,
  half_of_year_id,
  COUNT(*) OVER (PARTITION BY half_of_year_id)    AS Half_Year_Time_Span,
  MAX(day_id) OVER (PARTITION BY half_of_year_id) AS Half_Year_End_Date,
  year_id,
  COUNT(*) OVER (PARTITION BY year_id)    AS Year_Time_Span,
  MAX(day_id) OVER (PARTITION BY year_id) AS Year_End_Date
FROM base_calendar
ORDER BY day_id;
