CREATE TABLE FORWARDING_QUEUE (
  QUEUEID number NOT NULL,
  FILENAME varchar2(255) NOT NULL,
  FILEID number NOT NULL,
  ORIGINATING_CLIENTNAME varchar2(30) DEFAULT NULL,
  FORWARDING_CLIENTNAME varchar2(30) DEFAULT NULL,
  FORWARD_REQUEST_ON TIMESTAMP (4) WITH TIME ZONE,
  IWS_CASEID number DEFAULT NULL,
  CLONE_CASEID number DEFAULT NULL,
  STATUS varchar2(50) DEFAULT 'SUBMITTED',
  STATUS_MSG varchar2(1000) DEFAULT NULL,
  FORWARD_COMPLETE TIMESTAMP (4) WITH TIME ZONE
) tablespace snx_iws;

ALTER TABLE FORWARDING_QUEUE
    ADD CONSTRAINT FORWARDING_QUEUE_PK PRIMARY KEY ( QUEUEID ) using index tablespace snx_iws_inx;

CREATE SEQUENCE FORWARDING_QUEUE_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE OR REPLACE TRIGGER FORWARDING_QUEUE_QUEUEID_TGR before INSERT ON FORWARDING_QUEUE FOR EACH row
  BEGIN
    IF inserting THEN
      IF :NEW.QUEUEID IS NULL THEN
        SELECT FORWARDING_QUEUE_SEQ.nextval INTO :NEW.QUEUEID FROM dual;
      END IF;
    END IF;
  END;
/
