Drop table "SNX_IWS2"."SPINEGROUPS";
CREATE TABLE "SNX_IWS2"."SPINEGROUPS"
(
  GROUPID VARCHAR2(20) NOT NULL 
, GROUPNAME VARCHAR2(500) 
, PARENTGROUPID VARCHAR2(20) 
, CREATED_BY NUMBER
, CREATED_TIMESTAMP TIMESTAMP (4) WITH TIME ZONE
, UPDATED_BY NUMBER
, UPDATED_TIMESTAMP TIMESTAMP (4) WITH TIME ZONE
, CONSTRAINT SPINEGROUPS_PK PRIMARY KEY 
  (
    GROUPID 
  )
  ENABLE 
) 
TABLESPACE "SNX_IWS";

CREATE UNIQUE INDEX SPINEGROUPS_INDEX1 ON SPINEGROUPS (GROUPID, GROUPNAME, PARENTGROUPID) 
TABLESPACE "SNX_IWS_INX";
