  CREATE TABLE ICD10_SNOMED_MAP 
   (
	ICD10CMCODE VARCHAR2(200 BYTE), 
	SNOMED_CTCODE VARCHAR2(200 BYTE)
   ) TABLESPACE "SNX_IWS" ;

  CREATE Unique INDEX ICD10_SNOMED_MAP_UK1 ON ICD10_SNOMED_MAP (ICD10CMCODE) TABLESPACE "SNX_IWS_INX" ;
  CREATE INDEX ICD10_SNOMED_MAP_NK1 ON ICD10_SNOMED_MAP (SNOMED_CTCODE) TABLESPACE "SNX_IWS_INX" ;
