CREATE TABLE SC_GROUPS (
GroupId number NOT NULL,
GroupName varchar(50) NOT NULL,
CREATED_BY NUMBER DEFAULT NULL,
CREATED_TIMESTAMP TIMESTAMP(4) WITH TIME ZONE DEFAULT NULL,
UPDATED_BY NUMBER DEFAULT NULL,
UPDATED_TIMESTAMP TIMESTAMP(4) WITH TIME ZONE DEFAULT NULL
)tablespace snx_iws;

ALTER TABLE SC_GROUPS 
    ADD CONSTRAINT SC_GROUPS_PK PRIMARY KEY (GroupId) using index tablespace snx_iws_inx;

ALTER TABLE SC_GROUPS ADD CONSTRAINT SC_GROUPS_UK UNIQUE (GroupName) using index tablespace snx_iws_inx;

CREATE SEQUENCE SC_GROUPS_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE OR REPLACE TRIGGER SC_GROUPS_GroupId_TGR before INSERT ON SC_GROUPS FOR EACH row
  BEGIN
    IF inserting THEN
      select current_timestamp into :new.CREATED_TIMESTAMP from dual;
      IF :NEW.GroupId IS NULL THEN
        SELECT SC_GROUPS_SEQ.nextval INTO :NEW.GroupId FROM dual;
      END IF;
    END IF;
  END;
/