
CREATE TABLE SC_GROUPS_CLIENTS (
GROUPID number NOT NULL,
CLIENTID number NOT NULL,
CREATED_BY NUMBER DEFAULT NULL,
CREATED_TIMESTAMP TIMESTAMP(4) WITH TIME ZONE DEFAULT NULL,
UPDATED_BY NUMBER DEFAULT NULL,
UPDATED_TIMESTAMP TIMESTAMP(4) WITH TIME ZONE DEFAULT NULL
) tablespace snx_iws;

ALTER TABLE SC_GROUPS_CLIENTS ADD CONSTRAINT SC_GROUPS_CLIENTS_UK UNIQUE (GROUPID,CLIENTID) using index tablespace snx_iws_inx;

ALTER TABLE SC_GROUPS_CLIENTS ADD CONSTRAINT SC_GROUPS_CLIENTS_FK1 FOREIGN KEY ("GROUPID") REFERENCES SC_GROUPS (GroupId) ON DELETE CASCADE;

ALTER TABLE SC_GROUPS_CLIENTS ADD CONSTRAINT SC_GROUPS_CLIENTS_FK2 FOREIGN KEY ("CLIENTID") REFERENCES SC_CLIENTS (CLIENTID) ON DELETE CASCADE;
