set define off

DROP TABLE ROLEDOCTYPES CASCADE CONSTRAINTS;
CREATE TABLE ROLEDOCTYPES 
    ( 
     RDID INTEGER  NOT NULL , 
     ROLEID INTEGER ,
     DOCUMENTTYPEID INTEGER ,
     CREATED_TIMESTAMP TIMESTAMP (4) WITH TIME ZONE,
     CREATED_USERID INTEGER,
     UPDATED_TIMESTAMP TIMESTAMP (4) WITH TIME ZONE,
     UPDATED_USERID INTEGER                         
    ) 
;
ALTER TABLE ROLEDOCTYPES 
    ADD CONSTRAINT ROLEDOCTYPES_PK PRIMARY KEY ( RDID ) using index tablespace snx_iws_inx;
CREATE UNIQUE INDEX ROLEDOCTYPES_UK1 ON ROLEDOCTYPES 
    (ROLEID, DOCUMENTTYPEID) tablespace snx_iws_inx;

DROP SEQUENCE ROLEDOCTYPES_SEQ;
--Create Sequence
CREATE SEQUENCE ROLEDOCTYPES_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

--Create Trigger
CREATE OR REPLACE TRIGGER ROLEDOCTYPES_RDID_TGR before INSERT ON ROLEDOCTYPES FOR EACH row
  BEGIN
    IF inserting THEN
      select current_timestamp into :new.CREATED_TIMESTAMP from dual;
      IF :NEW.RDID IS NULL THEN
        SELECT ROLEDOCTYPES_SEQ.nextval INTO :NEW.RDID FROM dual;
      END IF;
    END IF;
  END;
/
