set define off

DROP TABLE PARALLELCASESTATUS CASCADE CONSTRAINTS;
CREATE TABLE PARALLELCASESTATUS 
    ( 
     PCSID INTEGER  NOT NULL , 
     CASEID INTEGER ,
     STAGEID INTEGER ,
     ROLEID INTEGER ,
     USERID INTEGER ,
     ISCOMPLETED VARCHAR2(1), 
     CREATED_TIMESTAMP TIMESTAMP (4) WITH TIME ZONE,
     CREATED_USERID INTEGER,
     CREATED_STAGEID INTEGER,
     UPDATED_TIMESTAMP TIMESTAMP (4) WITH TIME ZONE,
     UPDATED_USERID INTEGER,                         
     UPDATED_STAGEID INTEGER
    ) 
;
ALTER TABLE PARALLELCASESTATUS 
    ADD CONSTRAINT PARALLELCASESTATUS_PK PRIMARY KEY ( PCSID ) using index tablespace snx_iws_inx;
CREATE UNIQUE INDEX PARALLELCASESTATUS_UK1 ON PARALLELCASESTATUS 
    (CASEID, STAGEID, ROLEID, USERID) tablespace snx_iws_inx;
CREATE INDEX PARALLELCASESTATUS_NK1 ON PARALLELCASESTATUS 
    (CASEID, STAGEID, USERID, ISCOMPLETED) tablespace snx_iws_inx;

DROP SEQUENCE PARALLELCASESTATUS_SEQ;
--Create Sequence
CREATE SEQUENCE PARALLELCASESTATUS_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

--Create Trigger
CREATE OR REPLACE TRIGGER PARALLELCASESTATUS_PCSID_TGR before INSERT ON PARALLELCASESTATUS FOR EACH row
  BEGIN
    IF inserting THEN
      select current_timestamp into :new.CREATED_TIMESTAMP from dual;
      IF :NEW.PCSID IS NULL THEN
        SELECT PARALLELCASESTATUS_SEQ.nextval INTO :NEW.PCSID FROM dual;
      END IF;
    END IF;
  END;
/
