CREATE TABLESPACE "CONFLUENCE" DATAFILE '/ORACLE/NWJD01/confluence.dbf' SIZE 10M 
AUTOEXTEND ON NEXT 10240K MAXSIZE 16000M 
LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
DEFAULT STORAGE ( ENCRYPT ) ENCRYPTION USING 'AES256';

CREATE TABLESPACE "JIRA" DATAFILE '/ORACLE/NWJD01/jira.dbf' SIZE 10M 
AUTOEXTEND ON NEXT 10240K MAXSIZE 16000M 
LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
DEFAULT STORAGE ( ENCRYPT ) ENCRYPTION USING 'AES256';

CREATE TABLESPACE "CROWD" DATAFILE '/ORACLE/NWJD01/crowd.dbf' SIZE 10M 
AUTOEXTEND ON NEXT 10240K MAXSIZE 16000M 
LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
DEFAULT STORAGE ( ENCRYPT ) ENCRYPTION USING 'AES256';

-- USER SQL
CREATE USER CONFLUENCE IDENTIFIED BY Syn0d3x 
DEFAULT TABLESPACE "CONFLUENCE"
TEMPORARY TABLESPACE "TEMP";

CREATE USER JIRA IDENTIFIED BY Syn0d3x 
DEFAULT TABLESPACE "JIRA"
TEMPORARY TABLESPACE "TEMP";

CREATE USER CROWD IDENTIFIED BY Syn0d3x 
DEFAULT TABLESPACE "CROWD"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER CONFLUENCE QUOTA UNLIMITED ON CONFLUENCE;
ALTER USER JIRA QUOTA UNLIMITED ON JIRA;
ALTER USER CROWD QUOTA UNLIMITED ON CROWD;

-- ROLES
GRANT "RESOURCE" TO CONFLUENCE ;
GRANT "CONNECT" TO CONFLUENCE ;
GRANT "RESOURCE" TO JIRA ;
GRANT "CONNECT" TO JIRA ;
GRANT "RESOURCE" TO CROWD ;
GRANT "CONNECT" TO CROWD ;

grant create sequence to JIRA;
grant create trigger to JIRA;