CREATE TABLE "SNX_IWS2"."SYNID_GRAPHING_UNIT_MAP"
  (
    "SYNID"         VARCHAR2(20 BYTE) NOT NULL ENABLE,
    "GRAPHING_UNIT" VARCHAR2(50 BYTE),
    CONSTRAINT "SYNID_GRAPHING_UNIT_MAP_PK" PRIMARY KEY ("SYNID") USING INDEX TABLESPACE "SNX_IWS_INX" ENABLE
  ) TABLESPACE "SNX_IWS" ;