-- USER SQL
CREATE USER SNX_IWS2_MINIME IDENTIFIED BY "XXXXXX" 
DEFAULT TABLESPACE "SNX_IWS"
TEMPORARY TABLESPACE "TEMP";
-- QUOTAS
ALTER USER SNX_IWS2_MINIME QUOTA UNLIMITED ON SNX_IWS;
ALTER USER SNX_IWS2_MINIME QUOTA UNLIMITED ON SNX_IWS_INX;
-- ROLES
GRANT "RESOURCE" TO SNX_IWS2_MINIME ;
GRANT "CONNECT" TO SNX_IWS2_MINIME ;
-- SYSTEM PRIVILEGES
GRANT CREATE VIEW TO SNX_IWS2_MINIME ;
GRANT CREATE MATERIALIZED VIEW TO SNX_IWS2_MINIME ;
-- Object privileges
grant select on snx_iws2.cases to snx_iws2_minime;
grant select on snx_iws2.pages to snx_iws2_minime;
grant select on snx_iws2.dpentries to snx_iws2_minime;
