set define off

DROP TABLE ROLECATEGORIES CASCADE CONSTRAINTS;
CREATE TABLE ROLECATEGORIES 
    ( 
     RCID INTEGER  NOT NULL , 
     ROLEID INTEGER ,
     CATEGORY VARCHAR2(100) ,
     CREATED_TIMESTAMP TIMESTAMP (4) WITH TIME ZONE,
     CREATED_USERID INTEGER,
     UPDATED_TIMESTAMP TIMESTAMP (4) WITH TIME ZONE,
     UPDATED_USERID INTEGER                         
    ) 
;
ALTER TABLE ROLECATEGORIES 
    ADD CONSTRAINT ROLECATEGORIES_PK PRIMARY KEY ( RCID ) using index tablespace snx_iws_inx;
CREATE UNIQUE INDEX ROLECATEGORIES_UK1 ON ROLECATEGORIES 
    (ROLEID, CATEGORY) tablespace snx_iws_inx;

DROP SEQUENCE ROLECATEGORIES_SEQ;
--Create Sequence
CREATE SEQUENCE ROLECATEGORIES_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

--Create Trigger
CREATE OR REPLACE TRIGGER ROLECATEGORIES_RCID_TGR before INSERT ON ROLECATEGORIES FOR EACH row
  BEGIN
    IF inserting THEN
      select current_timestamp into :new.CREATED_TIMESTAMP from dual;
      IF :NEW.RCID IS NULL THEN
        SELECT ROLECATEGORIES_SEQ.nextval INTO :NEW.RCID FROM dual;
      END IF;
    END IF;
  END;
/
